src/Entity/Labels.php
<?php

namespace App\Entity;

use App\Repository\LabelsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LabelsRepository::class)
 */
class Labels
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $driver;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $zml_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $hostaddress;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $rows_on_page;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $cols_on_row;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $page_size;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $orientation;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $margin_left;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $margin_top;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $qr_size;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $label_width;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $label_height;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logo_src;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $logo_height;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $fontsize_1;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $fontsize_2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $attribute_1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $attribute_2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $attribute_3;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $attribute_4;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $creator;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $print_density;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $page_width;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $page_height;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $host;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $port;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDriver(): ?string
    {
        return $this->driver;
    }

    public function setDriver(string $driver): self
    {
        $this->driver = $driver;

        return $this;
    }

    public function getZmlCode(): ?string
    {
        return $this->zml_code;
    }

    public function setZmlCode(?string $zml_code): self
    {
        $this->zml_code = $zml_code;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getHostaddress(): ?string
    {
        return $this->hostaddress;
    }

    public function setHostaddress(?string $hostaddress): self
    {
        $this->hostaddress = $hostaddress;

        return $this;
    }

    public function getRowsOnPage(): ?int
    {
        return $this->rows_on_page;
    }

    public function setRowsOnPage(?int $rows_on_page): self
    {
        $this->rows_on_page = $rows_on_page;

        return $this;
    }

    public function getColsOnRow(): ?int
    {
        return $this->cols_on_row;
    }

    public function setColsOnRow(?int $cols_on_row): self
    {
        $this->cols_on_row = $cols_on_row;

        return $this;
    }

    public function getPageSize(): ?string
    {
        return $this->page_size;
    }

    public function setPageSize(?string $page_size): self
    {
        $this->page_size = $page_size;

        return $this;
    }

    public function getOrientation(): ?string
    {
        return $this->orientation;
    }

    public function setOrientation(?string $orientation): self
    {
        $this->orientation = $orientation;

        return $this;
    }

    public function getMarginLeft(): ?int
    {
        return $this->margin_left;
    }

    public function setMarginLeft(?int $margin_left): self
    {
        $this->margin_left = $margin_left;

        return $this;
    }

    public function getMarginTop(): ?int
    {
        return $this->margin_top;
    }

    public function setMarginTop(?int $margin_top): self
    {
        $this->margin_top = $margin_top;

        return $this;
    }

    public function getQrSize(): ?int
    {
        return $this->qr_size;
    }

    public function setQrSize(?int $qr_size): self
    {
        $this->qr_size = $qr_size;

        return $this;
    }

    public function getLabelWidth(): ?int
    {
        return $this->label_width;
    }

    public function setLabelWidth(?int $label_width): self
    {
        $this->label_width = $label_width;

        return $this;
    }

    public function getLabelHeight(): ?int
    {
        return $this->label_height;
    }

    public function setLabelHeight(?int $label_height): self
    {
        $this->label_height = $label_height;

        return $this;
    }

    public function getLogoSrc(): ?string
    {
        return $this->logo_src;
    }

    public function setLogoSrc(?string $logo_src): self
    {
        $this->logo_src = $logo_src;

        return $this;
    }

    public function getLogoHeight(): ?int
    {
        return $this->logo_height;
    }

    public function setLogoHeight(?int $logo_height): self
    {
        $this->logo_height = $logo_height;

        return $this;
    }

    public function getFontsize1(): ?int
    {
        return $this->fontsize_1;
    }

    public function setFontsize1(?int $fontsize_1): self
    {
        $this->fontsize_1 = $fontsize_1;

        return $this;
    }

    public function getFontsize2(): ?int
    {
        return $this->fontsize_2;
    }

    public function setFontsize2(?int $fontsize_2): self
    {
        $this->fontsize_2 = $fontsize_2;

        return $this;
    }

    public function getAttribute1(): ?string
    {
        return $this->attribute_1;
    }

    public function setAttribute1(?string $attribute_1): self
    {
        $this->attribute_1 = $attribute_1;

        return $this;
    }

    public function getAttribute2(): ?string
    {
        return $this->attribute_2;
    }

    public function setAttribute2(?string $attribute_2): self
    {
        $this->attribute_2 = $attribute_2;

        return $this;
    }

    public function getAttribute3(): ?string
    {
        return $this->attribute_3;
    }

    public function setAttribute3(?string $attribute_3): self
    {
        $this->attribute_3 = $attribute_3;

        return $this;
    }

    public function getAttribute4(): ?string
    {
        return $this->attribute_4;
    }

    public function setAttribute4(?string $attribute_4): self
    {
        $this->attribute_4 = $attribute_4;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getPrintDensity(): ?int
    {
        return $this->print_density;
    }

    public function setPrintDensity(?int $print_density): self
    {
        $this->print_density = $print_density;

        return $this;
    }

    public function getPageWidth(): ?int
    {
        return $this->page_width;
    }

    public function setPageWidth(?int $page_width): self
    {
        $this->page_width = $page_width;

        return $this;
    }

    public function getPageHeight(): ?int
    {
        return $this->page_height;
    }

    public function setPageHeight(?int $page_height): self
    {
        $this->page_height = $page_height;

        return $this;
    }

    public function getHost(): ?string
    {
        return $this->host;
    }

    public function setHost(?string $host): self
    {
        $this->host = $host;

        return $this;
    }

    public function getPort(): ?int
    {
        return $this->port;
    }

    public function setPort(?int $port): self
    {
        $this->port = $port;

        return $this;
    }
}

src/Controller/LabelsController.php
<?php

namespace App\Controller;

use App\Entity\Labels;
use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class LabelsController extends AbstractController
{
    /**
     * @Route("/labels", name="app_labels")
     */
    public function index(EntityManagerInterface $entityManager): Response
    {

        $repository = $entityManager->getRepository(User::class);
        $users = $repository->findBy([], ['lastname' => 'ASC']);
        $repository = $entityManager->getRepository(Labels::class);
        $labels = $repository->findAll();

        return $this->render('labels/index.html.twig', [
            'selection_list' => $labels,
            'users'           => $users
        ]);
    }

    /**
     * @Route ("/label/new", name="label_new", methods="GET")
     */
    public function new(EntityManagerInterface $entityManager) {
        $repository = $entityManager->getRepository(Labels::class);

        $label = new Labels();
        $label->setTitle('Untitled')
            ->setDriver('')
            ->setActive(1)
            ->setCreator($this->getUser())
            ->setCreated(new \DateTime())
        ;

        $entityManager->persist($label);
        $entityManager->flush();
        return $this->redirectToRoute('label_details', array('id' => $label->getId()));
    }

    /**
     * @Route ("/label/{id<(\d)+>}", name="label_details", methods={"GET"})
     */
    public function show($id, EntityManagerInterface $entityManager, LoggerInterface $logger){
        $repository = $entityManager->getRepository(Labels::class);
        $label = $repository->find($id);

        /** @var Labels|null $label */
        if (!$label) {
            throw $this->createNotFoundException('This label does not exist');
        }

        if ($label->getZmlCode()){
            $curl = curl_init();
            // adjust print density (8dpmm), label width (4 inches), label height (6 inches), and label index (0) as necessary
            $label_width   = 2;
            $label_height  = 1;
            $print_density = 8;

            if ($label->getPrintDensity() && $label->getLabelHeight() && $label->getLabelWidth()) {
                $label_width   = $label->getLabelWidth()/25.4;
                $label_height  = $label->getLabelHeight()/25.4;
                $print_density = $label->getPrintDensity();
            }
            $api_url = 'http://api.labelary.com/v1/printers/' . $print_density . 'dpmm/labels/' . $label_width . 'x' . $label_height . '/0/';
            curl_setopt($curl, CURLOPT_URL, $api_url);
            curl_setopt($curl, CURLOPT_POST, TRUE);
            curl_setopt($curl, CURLOPT_POSTFIELDS, $label->getZmlCode());
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
            $label_image = curl_exec($curl);

            if (curl_getinfo($curl, CURLINFO_HTTP_CODE) == 200) {

            } else {
                //dd("Error: $label_image");
                $logger->error($label_image);
                $label_image = '';
            }

            curl_close($curl);
        } else {
            $label_image = '';
        }

        return $this->render('labels/show.html.twig', array(
            'label' => $label,
            'label_image' => base64_encode($label_image),
        ));
    }

    /**
     * @Route ("/label/save", name="label_save", methods={"POST"})
     */
    public function save(EntityManagerInterface $entityManager, Request $request) {
        $repository = $entityManager->getRepository(Labels::class);
        $label = $repository->findOneBy(['id' => $request->request->get('id')]);
        if (!$label) {
            throw $this->createNotFoundException('This label does not exist');
        }

        $active = 0;
        if ($request->request->get('active') == '1') {
            $active = 1;
        }
        $label->setTitle($request->request->get('title'))
            ->setActive($active)
            ->setDriver($request->request->get('driver'))
            ->setZmlCode($request->request->get('zml_code'))
            ->setRowsOnPage((int) $request->request->get('rows_on_page'))
            ->setColsOnRow((int) $request->request->get('cols_on_row'))
            ->setPageSize((int) $request->request->get('page_size'))
            ->setPageHeight((int) $request->request->get('page_height'))
            ->setPageWidth((int) $request->request->get('page_width'))
            ->setOrientation($request->request->get('orientation'))
            ->setMarginLeft((int) $request->request->get('margin_left'))
            ->setMarginTop((int) $request->request->get('margin_top'))
            ->setQrSize((int) $request->request->get('qr_size'))
            ->setLabelWidth((int) $request->request->get('label_width'))
            ->setLabelHeight((int) $request->request->get('label_height'))
            ->setLogoHeight((int) $request->request->get('logo_height'))
            ->setLogoSrc($request->request->get('logo_src'))
            ->setFontsize1((int) $request->request->get('fontsize_1'))
            ->setFontsize2((int) $request->request->get('fontsize_2'))
            ->setPrintDensity((int) $request->request->get('print_density'))
            ->setAttribute1($request->request->get('attribute_1'))
            ->setAttribute2($request->request->get('attribute_2'))
            ->setAttribute3($request->request->get('attribute_3'))
            ->setAttribute4($request->request->get('attribute_4'))
            ;

        $entityManager->persist($label);
        $entityManager->flush();

        return $this->redirectToRoute('label_details', array('id' => $label->getId()));
    }


}

templates/labels/definition_tab.html.twig
<div role="tabpanel" id="tab-2" class="tab-pane active">

    <div class="row align-self-stretch zebra_only">

        <div class="col align-self-stretch">
            <div class="form-group">
                <label for="inputZmlCode" class="form-label">{% trans %} ZPL Code{% endtrans %}:</label>
                <textarea id="inputZmlCode" class="form-control" name="zml_code" rows="30">{{ label.zmlCode }}</textarea>
            </div>

            <div class="form-group">
                <label for="inputPrintDensity" class="form-label text-right">{% trans %} Print density {% endtrans %}</label>
                <select class="form-control custom-select" id="inputPrintDensity" name="print_density">
                    <option{% if label.printDensity == '6' %} selected="selected" {% endif%} value="6">152dpi (6dpmm)</option>
                    <option{% if label.printDensity == '8' %} selected="selected" {% endif%} value="8">203dpi (8dpmm)</option>
                    <option{% if label.printDensity == '12' %} selected="selected" {% endif%} value="12">300dpi (12dpmm)</option>
                    <option{% if label.printDensity == '24' %} selected="selected" {% endif%} value="24">600dpi (24dpmm)</option>
                </select>
            </div>

        </div>

        <div class="col align-self-stretch">
            <div class="mb-0">{% trans %} Preview {% endtrans %}:</div>
            {% if label_image %}
                <img style="width: {{ label.labelWidth }}mm; height: {{ label.labelHeight }}mm" class="border rounded mt-2" src="data:image/png;base64,{{ label_image }}">
            {% endif %}
        </div>

    </div>

    <div class="row align-self-stretch pdf_only">
        <div class="col align-self-stretch">
            <div class="form-group">
                <label for="inputQrSize" class="form-label">{% trans %} QR code size {% endtrans %} [mm]</label>
                <input type="number" class="form-control" id="inputQrSize" name="qr_size" value="{{ label.qrSize }}">
            </div>
            <div class="form-group">
                <label for="inputLogoSrc" class="form-label">{% trans %} Logo source {% endtrans %} [URI]</label>
                <input type="url" class="form-control" id="inputLogoSrc" name="logo_src" value="{{ label.logoSrc }}">
            </div>
            <div class="form-group">
                <label for="inputLogoHeight" class="form-label">{% trans %} Logo height {% endtrans %} [mm]</label>
                <input type="number" class="form-control" id="inputLogoHeight" name="logo_height" value="{{ label.logoHeight }}">
            </div>
            <div class="form-group">
                <label for="inputFontsize1" class="form-label">{% trans %} Font size 1st attribute {% endtrans %} [pt]</label>
                <input type="number" class="form-control" id="inputFontsize1" name="fontsize_1" value="{{ label.fontsize1 }}">
            </div>
            <div class="form-group">
                <label for="inputFontsize2" class="form-label">{% trans %} Font size other attributes {% endtrans %} [pt]</label>
                <input type="number" class="form-control" id="inputFontsize2" name="fontsize_2" value="{{ label.fontsize2 }}">
            </div>
            <div class="form-group">
                <label for="inputAttribute1" class="form-label">{% trans %} Attribute {% endtrans %} 1</label>
                <input type="text" class="form-control" id="inputAttribute1" name="attribute_1" value="{{ label.attribute1 }}">
            </div>
            <div class="form-group">
                <label for="inputAttribute2" class="form-label">{% trans %} Attribute {% endtrans %} 2</label>
                <input type="text" class="form-control" id="inputAttribute2" name="attribute_2" value="{{ label.attribute2 }}">
            </div>
            <div class="form-group">
                <label for="inputAttribute3" class="form-label">{% trans %} Attribute {% endtrans %} 3</label>
                <input type="text" class="form-control" id="inputAttribute3" name="attribute_3" value="{{ label.attribute3 }}">
            </div>
            <div class="form-group">
                <label for="inputAttribute4" class="form-label">{% trans %} Attribute {% endtrans %} 4</label>
                <input type="text" class="form-control" id="inputAttribute4" name="attribute_4" value="{{ label.attribute4 }}">
            </div>

            <hr>
            <h2>{% trans %} Page settings {% endtrans %}</h2>

            <div class="form-group">
                <label for="inputColsOnRow" class="form-label">{% trans %} Columns per row {% endtrans %}</label>
                <input type="number" class="form-control" id="inputColsOnRow" name="cols_on_row" value="{{ label.colsOnRow }}">
            </div>
            <div class="form-group">
                <label for="inputRowsOnPage" class="form-label">{% trans %} Rows on page {% endtrans %}</label>
                <input type="number" class="form-control" id="inputRowsOnPage" name="rows_on_page" value="{{ label.rowsOnPage }}">
            </div>
            <div class="form-group">
                <label for="inputPageWidth" class="form-label">{% trans %} Page width {% endtrans %} [mm]</label>
                <input type="number" class="form-control" id="inputPageWidth" name="page_width" value="{{ label.pageWidth }}">
            </div>
            <div class="form-group">
                <label for="inputPageHeight" class="form-label">{% trans %} Page height {% endtrans %} [mm]</label>
                <input type="number" class="form-control" id="inputPageHeight" name="page_height" value="{{ label.pageHeight }}">
            </div>
            <div class="form-group">
                <label for="inputOrientation" class="form-label text-right">{% trans %} Page orientation {% endtrans %}</label>
                <select class="form-control custom-select" id="inputOrientation" name="orientation">
                    <option{% if label.orientation == 'P' %} selected="selected" {% endif%} value="P">{% trans %} Portrait {% endtrans %}</option>
                    <option{% if label.orientation == 'L' %} selected="selected" {% endif%} value="L">{% trans %} Landscape {% endtrans %}</option>
                </select>
            </div>
            <div class="form-group">
                <label for="inputMarginLeft" class="form-label">{% trans %} Margin left {% endtrans %} [mm]</label>
                <input type="number" class="form-control" id="inputMarginLeft" name="margin_left" value="{{ label.marginLeft }}">
            </div>
            <div class="form-group">
                <label for="inputMarginTop" class="form-label">{% trans %} Margin top {% endtrans %} [mm]</label>
                <input type="number" class="form-control" id="inputMarginTop" name="margin_top" value="{{ label.marginTop }}">
            </div>

        </div>
        <div class="col align-self-stretch">
            <div class="mb-0">{% trans %} Preview {% endtrans %}:</div>
            <div class="">
                <canvas id="label" class="border rounded m-0 mr-0 ml-0"></canvas>
            </div>
            <div class="">
                <input type="hidden" id="QrDontPanic" value="{{ asset('assets/img/qr-dont-panic-at.png') }}">
                <input type="hidden" id="Logo" value="{{ label.logoSrc }}">
            </div>
            

        </div>

    </div>

</div>

templates/labels/global_tab.html.twig
<div role="tabpanel" id="tab-1" class="tab-pane">
    <div class="form-group required">
        <label for="inputTitle" class="form-label">{% trans %} Title {% endtrans %}</label>
        <input type="text" class="form-control" id="inputTitle" name="title"  value="{{ label.title }}">
    </div>

    <div class="form-group required">
        <label for="inputDriver" class="form-label text-right">{% trans %} Output format {% endtrans %}</label>
        <select class="form-control custom-select" id="inputDriver" name="driver">
            <option{% if label.driver == 'ZPL' %} selected="selected" {% endif%} value="ZPL">Zebra Programming Language (ZPL)</option>
        </select>
    </div>

    <div class="form-group ">
        <input type="checkbox" value="1" class="form-check-inline" id="inputActive" name="active"  {% if label.active == 1 %} checked="checked" {% endif  %}>
        <label for="inputActive" class="form-label text-right">{% trans %} Active {% endtrans %}</label>

    </div>

    <div class="form-group required">
        <label for="inputLabelWidth" class="form-label">{% trans %} Label width {% endtrans %} [mm]</label>
        <input type="number" class="form-control" id="inputLabelWidth" name="label_width"  value="{{ label.labelWidth }}">
    </div>

    <div class="form-group required">
        <label for="inputLabelHeight" class="form-label">{% trans %} Label height {% endtrans %} [mm]</label>
        <input type="number" class="form-control" id="inputLabelHeight" name="label_height"  value="{{ label.labelHeight }}">
    </div>


</div>

templates/labels/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Labels{% endblock %}
{% block filter %}
{% endblock %}



{% block content %}



    <div class="px-4 mt-4">
        <ol class="breadcrumb bg-white border-white">
            <li class="breadcrumb-item"><a href="{{ path('rfc_index') }}"><span>{% trans %} Home {% endtrans %}</span></a></li>
            <li class="breadcrumb-item"><a href="{{ path('app_labels') }}"><span>{% trans %} Labels {% endtrans %}</span></a></li>
        </ol>
        <div class="row">
            <div class="col">
                <a href="{{ path('label_new') }}"> <button class="btn btn-primary new" type="button">{% trans %} New {% endtrans %}</button></a>
                <div class="table-responsive mt-3">
                    <div class="table-responsive mt-3">
                        <table class="table">
                            <thead>
                            <tr class="d-flex">
                                <th class="col-1">#</th>
                                <th class="col-5">{% trans %} Title {% endtrans %}</th>
                                <th class="col-6">{% trans %} Output format {% endtrans %}</th>
                            </tr>
                            </thead>
                            <tbody id="labelsList">
                            {% for item in selection_list %}
                                <tr class="d-flex">
                                    <td  class="col-1"><a href="{{ path('label_details', {'id': item.id }) }}">{{ item.id }}</a> </td>
                                    <td class="col-5"><a href="{{ path('label_details', {'id': item.id }) }}">{{ item.title }}</a></td>
                                    <td class="col-6">{{ item.driver }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('assets/js/chosen.jquery.js') }}"></script>
    <script src="{{ asset('assets/js/rfc_standardchanges.js') }}"></script>
{% endblock %}

templates/labels/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}Labels{% endblock %}
{% block filter %}
{% endblock %}



{% block content %}



    <div class="px-4 mt-4">
        <ol class="breadcrumb bg-white border-white">
            <li class="breadcrumb-item"><a href="{{ path('rfc_index') }}"><span>{% trans %} Home {% endtrans %}</span></a></li>
            <li class="breadcrumb-item"><a href="{{ path('app_labels') }}"><span>{% trans %} Labels {% endtrans %}</span></a></li>
            <li class="breadcrumb-item"><a href="{{ path('label_details', {'id': label.id})}}"><span>{{ label.title }}</span></a></li>
        </ol>

        <div class=" border rounded-0 border-light p-4">
            <form class="" method="post" action="{{ path('label_save') }}">
                <input type="hidden" name="id" value="{{ label.id }}">
                <button class="btn btn-primary" type="submit">{% trans %} Save {% endtrans %}</button>
                <hr>

                <div>
                    <ul role="tablist" class="nav nav-tabs">
                        <li role="presentation" class="nav-item"><a role="tab" data-toggle="tab" class="nav-link" href="#tab-1">{% trans %} Global {% endtrans %}</a></li>
                        <li role="presentation" class="nav-item"><a role="tab" data-toggle="tab" class="nav-link active" href="#tab-2">{% trans %} Label definition {% endtrans %}</a></li>
                    </ul>
                </div>


                <div class="tab-content border rounded-0 border-top-0 p-4">
                    {% include "labels/global_tab.html.twig" %}
                    {% include "labels/definition_tab.html.twig" %}
                </div>

            </form>

        </div>
    </div>

{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('assets/js/labels.js') }}"></script>
    <script src="{{ asset('assets/js/chosen.jquery.js') }}"></script>
{% endblock %}