src/Entity/Rfc.php
<?php

namespace App\Entity;

use App\Repository\RfcRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RfcRepository::class)
 */
class Rfc
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $referenced_ticketid;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $consequences;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $affected_components;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $customfields;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $commentary;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $affected_componentsstore;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $creator;

    /**
     * @ORM\ManyToOne(targetEntity=Departments::class, inversedBy="rfcs")
     */
    private $department;

    /**
     * @ORM\ManyToOne(targetEntity=Costcenters::class, inversedBy="rfcs")
     */
    private $costcenter;

    /**
     * @ORM\ManyToOne(targetEntity=Reasons::class, inversedBy="rfcs")
     */
    private $reason;

    /**
     * @ORM\ManyToOne(targetEntity=Status::class, inversedBy="rfcs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity=Priorities::class, inversedBy="rfcs")
     */
    private $priority;

    /**
     * @ORM\ManyToOne(targetEntity=Projects::class, inversedBy="rfcs")
     */
    private $project;

    /**
     * @ORM\OneToMany(targetEntity=RfcNotices::class, mappedBy="rfc", orphanRemoval=true)
     */
    private $rfcNotices;

    /**
     * @ORM\OneToMany(targetEntity=RfcWorkflows::class, mappedBy="rfc")
     */
    private $rfcWorkflows;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $attachment;

    /**
     * @ORM\ManyToOne(targetEntity=Datetypes::class)
     */
    private $datetype;

    /**
     * @ORM\ManyToOne(targetEntity=BusinessProcesses::class)
     */
    private $business_process;

    /**
     * @ORM\OneToOne(targetEntity=RfcClassifications::class, mappedBy="rfc")
     */
    private $rfc_classification;

    /**
     * @ORM\OneToMany(targetEntity=RfcBpoFeedback::class, mappedBy="rfc", orphanRemoval=true)
     */
    private $rfcBpoFeedback;

    public function __construct()
    {
        $this->rfcNotices = new ArrayCollection();
        $this->rfcWorkflows = new ArrayCollection();
        $this->rfcBpoFeedback = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getReferencedTicketid(): ?string
    {
        return $this->referenced_ticketid;
    }

    public function setReferencedTicketid(?string $referenced_ticketid): self
    {
        $this->referenced_ticketid = $referenced_ticketid;

        return $this;
    }

    public function getConsequences(): ?string
    {
        return $this->consequences;
    }

    public function setConsequences(?string $consequences): self
    {
        $this->consequences = $consequences;

        return $this;
    }

    public function getAffectedComponents(): ?string
    {
        return $this->affected_components;
    }

    public function setAffectedComponents(string $affected_components): self
    {
        $this->affected_components = $affected_components;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getCustomfields(): ?string
    {
        return $this->customfields;
    }

    public function setCustomfields(?string $customfields): self
    {
        $this->customfields = $customfields;

        return $this;
    }

    public function getCommentary(): ?string
    {
        return $this->commentary;
    }

    public function setCommentary(?string $commentary): self
    {
        $this->commentary = $commentary;

        return $this;
    }

    public function getAffectedComponentsstore(): ?string
    {
        return $this->affected_componentsstore;
    }

    public function setAffectedComponentsstore(?string $affected_componentsstore): self
    {
        $this->affected_componentsstore = $affected_componentsstore;

        return $this;
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    public function getDepartment(): ?Departments
    {
        return $this->department;
    }

    public function setDepartment(?Departments $department): self
    {
        $this->department = $department;

        return $this;
    }

    public function getCostcenter(): ?Costcenters
    {
        return $this->costcenter;
    }

    public function setCostcenter(?Costcenters $costcenter): self
    {
        $this->costcenter = $costcenter;

        return $this;
    }

    public function getReason(): ?Reasons
    {
        return $this->reason;
    }

    public function setReason(?Reasons $reason): self
    {
        $this->reason = $reason;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getPriority(): ?Priorities
    {
        return $this->priority;
    }

    public function setPriority(?Priorities $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getProject(): ?Projects
    {
        return $this->project;
    }

    public function setProject(?Projects $project): self
    {
        $this->project = $project;

        return $this;
    }

    /**
     * @return Collection|RfcNotices[]
     */
    public function getRfcNotices(): Collection
    {
        return $this->rfcNotices;
    }

    public function addRfcNotice(RfcNotices $rfcNotice): self
    {
        if (!$this->rfcNotices->contains($rfcNotice)) {
            $this->rfcNotices[] = $rfcNotice;
            $rfcNotice->setRfc($this);
        }

        return $this;
    }

    public function removeRfcNotice(RfcNotices $rfcNotice): self
    {
        if ($this->rfcNotices->removeElement($rfcNotice)) {
            // set the owning side to null (unless already changed)
            if ($rfcNotice->getRfc() === $this) {
                $rfcNotice->setRfc(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|RfcWorkflows[]
     */
    public function getRfcWorkflows(): Collection
    {
        return $this->rfcWorkflows;
    }

    public function addRfcWorkflow(RfcWorkflows $rfcWorkflow): self
    {
        if (!$this->rfcWorkflows->contains($rfcWorkflow)) {
            $this->rfcWorkflows[] = $rfcWorkflow;
            $rfcWorkflow->setRfc($this);
        }

        return $this;
    }

    public function removeRfcWorkflow(RfcWorkflows $rfcWorkflow): self
    {
        if ($this->rfcWorkflows->removeElement($rfcWorkflow)) {
            // set the owning side to null (unless already changed)
            if ($rfcWorkflow->getRfc() === $this) {
                $rfcWorkflow->setRfc(null);
            }
        }

        return $this;
    }

    public function getAttachment(): ?string
    {
        return $this->attachment;
    }

    public function setAttachment(?string $attachment): self
    {
        $this->attachment = $attachment;

        return $this;
    }

    public function getDatetype(): ?Datetypes
    {
        return $this->datetype;
    }

    public function setDatetype(?Datetypes $datetype): self
    {
        $this->datetype = $datetype;

        return $this;
    }

    public function getBusinessProcess(): ?BusinessProcesses
    {
        return $this->business_process;
    }

    public function setBusinessProcess(?BusinessProcesses $business_process): self
    {
        $this->business_process = $business_process;

        return $this;
    }

    public function getRfcClassification(): ?RfcClassifications
    {
        return $this->rfc_classification;
    }

    public function setRfcClassification(?RfcClassifications $rfcClassifications): self
    {
        $this->business_process = $rfcClassifications;

        return $this;
    }

    /**
     * @return Collection|RfcBpoFeedback[]
     */
    public function getRfcBpoFeedback(): Collection
    {
        return $this->rfcBpoFeedback;
    }

templates/rfc/submission_ro_tab.html.twig
<div role="tabpanel" class="tab-pane {%
    if rfc.status.const == 'C__STATUS__DRAFT' or
    rfc.status.const == 'C__STATUS__CABKO' or
    rfc.status.const == 'C__STATUS__COMPLETE' or
    rfc.status.const == 'C__STATUS__FAILED'
%} active {% endif %}" id="tab-1">

    <form method="post" action="{{ path('rfc_save') }}" id="submissionForm" enctype="multipart/form-data">
        <input type="hidden" name="id" value="{{ rfc.id }}">
        <div class="form-row text-left">
            <div class="col">

            </div>
        </div>
        <hr>
        <div class="row align-self-stretch">
            <div class="col align-self-stretch border-right">
                <div class="row pt-2 mb-2">
                    <div class="col-md-12 mb-2">
                        {% trans %} Title {% endtrans %}
                    </div>
                    <div class="col-md-12">
                        {{ rfc.title }}
                    </div>
                </div>
                <hr>
                <div class="row pt-2 mb-2">
                    <div class="col-md-12 mb-2">
                        {% trans %} Descripton {% endtrans %}
                    </div>
                    <div class="col-md-12">
                        {{ rfc.description |striptags | markdown_to_html }}
                    </div>
                </div>
                <hr>
                <div class="row pt-2 mb-2">
                    <div class="col-md-12 mb-2">
                        {% trans %} Consequences {% endtrans %}
                    </div>
                    <div class="col-md-12">
                        {{ rfc.consequences |striptags | markdown_to_html }}
                    </div>
                </div>


            </div>
            <div class="col align-self-stretch border-right">
                <div class="row pt-2 mb-2">
                    <div class="col-md-12 mb-2">
                        {% trans %} Applicant {% endtrans %}
                    </div>
                    <div class="col-md-12">
                        {{ rfc.creator.firstname }} {{ rfc.creator.lastname }} ({{ rfc.creator.username }})
                    </div>
                </div>
                <hr>
                <div class="row pt-2 mb-2">
                    <div class="col-md-12 mb-2">
                        {% trans %} Section {% endtrans %}
                    </div>
                    <div class="col-md-12">
                        {% if rfc.costcenter %} {{ rfc.costcenter.title }} {% endif %}
                    </div>
                </div>
                <hr>
                <div class="row pt-2 mb-2">
                    <div class="col-md-12 mb-2">
                        {% trans %} Business process {% endtrans %}
                    </div>
                    <div class="col-md-12">
                        {% if rfc.businessProcess %}{{ rfc.businessProcess.title }}{% endif %}
                    </div>
                </div>
                <hr>
                <div class="row pt-2 mb-2">
                    <label class="col-md-12">
                        {% trans %} Target date {% endtrans %} ({{ rfc.datetype.title|trans }})
                    </label>
                    <div class="col-md-12">
                        {{ rfc.date|date("Y-m-d") }}
                    </div>
                </div>
                <hr>
                <div class="row pt-2 mb-2">
                    <label class="col-md-12">{% trans %} Affected services {% endtrans %}</label>

                    <div class="col-md-12">
                        <ul id="affectedComponentsstore" class="list-group"
                            data-affected_components_store="{{ rfc.affectedComponentsstore }}">
                            {% for affected_component in affacted_components %}
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    {{ affected_component.title }}
                                    <span>
                                        <a href="{{ config.idoit_url }}/?objID={{ affected_component.id }}" target="_blank">
                                            <span class="fa fa-external-link"></span>
                                        </a>
                                    </span>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

            </div>
            <div class="col align-self-stretch">
                <div class="row pt-2 mb-2">
                    <label class="col-md-12">{% trans %} Reason for execution {% endtrans %}</label>

                    <div class="col-md-12">
                        {% if rfc.reason %} {{ rfc.reason.title|trans}} {% endif %}
                    </div>
                </div>

                {% for customfield in customfields %}
                    <div class="row pt-2 mb-2">
                        {% if customfield.type == 1 %} {# Text #}
                            <label class="col-md-12">{{ customfield.label }}</label>
                            <div class="col-md-12">
                                {% if customfield['value'] is defined %}
                                    {{ customfield.value }}
                                {% endif %}
                            </div>
                        {%  elseif customfield.type == 2 %} {# checkbox #}
                            <div class="col-md-12">
                                {% if customfield['value'] is defined %}
                                    <span class="fa fa-check-square"></span>
                                {% else %}
                                    <span class="fa fa-square-o"></span>
                                {% endif %}
                                <label for="{{ customfield.id }}" class="form-check-label">{{ customfield.label }}</label>
                            </div>
                        {%  elseif customfield.type == 3 %} {# Textarea #}
                            <label class="col-md-12">{{ customfield.label }}</label>
                            <div class="col-md-12">
                                {% if customfield['value'] is defined %}
                                    {{ customfield.value | markdown_to_html }}
                                {% endif %}
                            </div>
                        {%  elseif customfield.type == 4 %} {# Date #}
                            <label class="col-md-12">{{ customfield.label }}</label>
                            <div class="col-md-12">
                                {% if customfield['value'] is defined %}
                                    {{ customfield.value }}
                                {% endif %}
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}

                <hr>
            
                <div class="row pt-2 mb-2">
                    <label class="col-md-12">{% trans %} Priority {% endtrans %}</label>
                    <div class="col-md-12" >
                        {% if rfc.priority.id %} {{ rfc.priority.title|trans }} {% endif %}
                    </div>
                </div>
                <hr>
                <div class="row pt-2 mb-2"><label class="col-md-12">{% trans %} Project {% endtrans %}</label>
                    <div class="col-md-12">
                        {% if rfc.project %} {{ rfc.project.title }} {% endif %}
                    </div>
                </div>
                <hr>
                <div class="row pt-2 mb-2">
                    <label class="col-md-12">{% trans %} Ticket{% endtrans %}</label>
                    <div class="col-md-12">
                        {% if ticket %}
                                <dl class="row">
                                    {% if ticket.id is defined and ticket.id != '' %}
                                        <dt class="col-sm-3">{% trans %} Ticket ID: {% endtrans %}</dt>
                                        <dd class="col-sm-9"><a target="ticket_window" onclick="window.open('{{ ticket.url }}', 'ticket_window');" href="{{ ticket.url }}">{{ ticket.id }} <span class="fa fa-external-link"></span></a></dd>
                                    {% endif %}
                                    {% if ticket.number is defined and ticket.number != '' %}
                                        <dt class="col-sm-3">{% trans %} Number: {% endtrans %}</dt>
                                        <dd class="col-sm-9">{{ ticket.number }}</dd>
                                    {% endif %}
                                    {% if ticket.title is defined and ticket.title != '' %}
                                        <dt class="col-sm-3">{% trans %} Title: {% endtrans %} </dt>
                                        <dd class="col-sm-9">{{ ticket.title }}</dd>
                                    {% endif %}
                                </dl>
                        {% endif %}
                    </div>

                </div>
                <hr>
                <div class="row pt-2 mb-2">

                    <label class="col-md-12">{% trans %} Attachments {% endtrans %}</label>

                    <div class="col-md-12">
                        <ul id="Attachments" class="list-group mt-3 mb-3"
                            data-attachments="{{ rfc.attachment|json_encode }}">
                            {% for attachment in attachments %}
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    {{ attachment.original_name }}
                                    <span>
                                        <a href="{{ path('rfc_attachment_download', {'saved_name': attachment.saved_name, 'original_name': attachment.original_name} ) }}">
                                            <span class="fa fa-download"></span>
                                        </a>
                                    </span>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </form>


</div>

templates/rfc/submission_tab.html.twig
<div role="tabpanel" class="tab-pane {%
    if rfc.status.const == 'C__STATUS__DRAFT' or
    rfc.status.const == 'C__STATUS__CABKO' or
    rfc.status.const == 'C__STATUS__COMPLETE' or
    rfc.status.const == 'C__STATUS__FAILED'
%} active {% endif %}" id="tab-1">

    <form method="post" action="{{ path('rfc_save') }}" id="submissionForm" enctype="multipart/form-data">
        <input type="hidden" name="id" value="{{ rfc.id }}">
        <div class="form-row text-left">
            <div class="col">
                <div class="btn-group">
                    <button class="btn btn-primary" type="submit" name="status" value="C__STATUS__INCOME">{% trans %} Submit request {% endtrans %}</button>
                    <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-expanded="false"  id="dropdownMenuReference" data-reference="parent">
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuReference">
                        <button class="dropdown-item btn btn-outline-secondary" type="submit" name="status" value="C__STATUS__DRAFT">{% trans %} Save draft {% endtrans %}</button>
                        <button class="dropdown-item btn btn-outline-secondary" type="button" name="delete" value="{{ path('rfc_delete', {id: rfc.id}) }}">{% trans %} Delete draft {% endtrans %}</button>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="row align-self-stretch">
            <div class="col align-self-stretch border-right">
                <div class="form-group required">
                    <label for="rfcTitle">{% trans %} Title {% endtrans %}</label>
                    <input type="text" class="form-control" name="title" id="rfcTitle" value="{{ rfc.title }}" required />
                </div>

                <div class="form-group  {% if system_config.optional_submission_description == null %}required{% endif%}">
                    <label for="rfcDescription">{% trans %} Description {% endtrans %}</label>
                    <textarea class="form-control" rows="7" id="rfcDescription" name="description" {% if system_config.optional_submission_consequences == null %}required{% endif%}>{{ rfc.description|striptags }}</textarea>
                </div>

                <div class="form-group  {% if system_config.optional_submission_consequences == null %}required{% endif%}">
                    <label for="rfcConsequences">{% trans %} Consequences {% endtrans %}</label>
                    <textarea class="form-control" rows="7" id="rfcConsequences" name="consequences" {% if system_config.optional_submission_consequences == null %}required{% endif%}>{{ rfc.consequences|striptags }}</textarea>
                </div>
            </div>
            <div class="col align-self-stretch border-right">

                <div class="form-group required"><label>{% trans %} Applicant {% endtrans %}</label>
                    {% if 'C__ROLES__CM' in app.user.roles %}
                        <select class="custom-select chosen-select" name="creator" required>
                            <option value="" selected>
                            {% for user in users %}
                            <option value="{{ user.id }}" {% if rfc.creator and rfc.creator.id == user.id %}selected="selected"{% endif %}>{{ user.firstname }} {{ user.lastname }} ({{ user.username }})</option>
                            {% endfor %}
                        </select>
                    {% else %}
                        <input type="hidden" name="creator" value="{{ rfc.creator.id }}" >
                        <input type="text" class="form-control" readonly value="{{ rfc.creator.firstname }} {{ rfc.creator.lastname }} ({{ rfc.creator.username }})">
                    {% endif %}
                </div>

                <div class="form-group {% if system_config.section_required %}required{% endif %}"><label>{% trans %} Section {% endtrans %}</label>
                    <select class="custom-select" name="costcenters" {% if system_config.section_required %}required="required"{% endif %} >
                        <option value="" selected></option>
                        {% for costcenter in costcenters %}
                        <option value="{{ costcenter.id }}" {% if rfc.costcenter and rfc.costcenter.id == costcenter.id %}selected="selected"{% endif %}>{{ costcenter.title }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group {% if system_config.process_required %}required{% endif %}"><label>{% trans %} Business process {% endtrans %}</label>
                    <select class="custom-select" name="business_process" {% if system_config.process_required %}required="required"{% endif %} >
                        <option value=""></option>
                        {% for business_process in business_processes %}
                            <option value="{{ business_process.id }}" {% if rfc.businessProcess and rfc.businessProcess.id == business_process.id %} selected="selected" {% endif %}>{{ business_process.title }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group"><label>{% trans %} Target date {% endtrans %}</label>

                    <div class="input-group required">
                        <input type="date" name="date" class="input-group-prepend form-control" value="{{ rfc.date|date("Y-m-d") }}" required>
                        <div class="input-group-append">
                            <select class="custom-select" name="date_type" required>
                                <option selected></option>
                                {% for date_type in date_types %}
                                    <option value="{{ date_type.id }}" {% if rfc.datetype.id == date_type.id %} selected="selected" {% endif %}>{{ date_type.title }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>

                <div class="form-group"><label>{% trans %} Affected services {% endtrans %}</label>
                    {{ include('idoit/object_browser.html.twig') }}
                    <input type="hidden" name="affectedComponentsstore" id="inputAffectedComponentsstore" value="{{ rfc.affectedComponentsstore }}">
                    <ul id="affectedComponentsstore" class="list-group" data-affected_components_store="{{ rfc.affectedComponentsstore }}">
                        {% for affected_component in affacted_components %}
                            <li class="list-group-item d-flex justify-content-between align-items-center" data-affected_component_id="{{ affected_component.id }}">
                                {{ affected_component.title }}
                                <span class="fa fa-remove clickable"></span>

                            </li>

                        {% endfor %}

                    </ul>
                    <div class="mt-3">
                        <button type="button" data-toggle="modal" data-target="#CmdbBrowser" class="btn btn-outline-primary">{% trans %} Add service {% endtrans %}</button>
                    </div>


                </div>

            </div>
            <div class="col align-self-stretch">
                <div class="form-group required">
                    <label>{% trans %} Reason for execution {% endtrans %}</label>
                    <select class="custom-select reason" name="reason" required>
                        <option value=""></option>
                        {% for reason in reasons %}
                            <option value="{{ reason.id }}" {% if (rfc.reason and rfc.reason.id == reason.id) or (reason.isDefault) %} selected="selected" {% endif %}>{{ reason.title|trans }}</option>
                        {% endfor %}

                    </select>
                </div>
                <div id="additional_fields" data-stored_values='{{ rfc.customfields }}'></div>
                <div class="form-group">
                    <label>{% trans %} Priority {% endtrans %}</label>
                    <select class="custom-select" name="priority">
                        {% for priority in priorities %}
                            <option value="{{ priority.id }}" {% if rfc.priority.id == priority.id %} selected="selected" {% endif %}>{{ priority.title|trans }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group project"><label>{% trans %} Project {% endtrans %}</label>
                    <select class="custom-select project" name="project">
                        <option value="" ></option>
                        {% for project in projects %}
                            <option value="{{ project.id }}" {% if rfc.project and rfc.project.id == project.id %} selected="selected" {% endif %}>{{ project.title }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group ticket">
                    <label>{% trans %} Ticket ID {% endtrans %} </label>
                    <input type="hidden" id="tts_driver" name="tts_driver" value="{{ tts_config.driver }}">
                    <input type="text" class="form-control ticket" name="referenced_ticket" value="{% if ticket %}{{ ticket.id }}{% endif %}" placeholder="{% if tts_config.driver == 'Zammad' %}autogenerated when left empty{% endif %}">
                </div>

                <div class="form-group">
                    <label>{% trans %} Attachments {% endtrans %}</label>



                    <ul id="Attachments" class="list-group mt-3 mb-3" data-attachments="{{ rfc.attachment|json_encode }}">
                        {% for attachment in attachments %}
                            <li class="list-group-item d-flex justify-content-between align-items-center" data-attachment_name="{{ attachment|json_encode }}">
                                {{ attachment.original_name }}
                                <span class="fa fa-remove clickable"></span>

                            </li>

                        {% endfor %}

                    </ul>

                    <input type="file" class="form-control-file submission-attachment" name="attachment[]" multiple>

                </div>
            </div>
        </div>
    </form>


</div>

templates/rfc/validation_ro_tab.html.twig
<div role="tabpanel" class="tab-pane {% if rfc.status.const == "C__STATUS__VALIDATION" %} active {% endif %}" id="tab-7">



    <div class="col align-self-stretch">
                <hr>


        <div class="col-md-12 mb-2">
            {% trans %} Validation commentary {% endtrans %}
        </div>
        <div class="col-md-12">
            {{ rfc.commentary |striptags | markdown_to_html }}
        </div>

    </div>

</div>